<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" Version="1.75.0" />
    <PackageReference Include="Google.Apis.Calendar.v3" Version="1.75.0.4206" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AcademiaTennisDAL\AcademiaTennisDAL.csproj" />
  </ItemGroup>

</Project>
