// <auto-generated />
using System;
using AcademiaTennisDAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcademiaTennisDAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615165207_AgregaIdProfesorACurso")]
    partial class AgregaIdProfesorACurso
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AcademiaTennisDAL.Entities.AlertaAbandono", b =>
                {
                    b.Property<int>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlerta"));

                    b.Property<string>("AccionTomada")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaAlerta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaGestion")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdAlumno")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("IdAlerta");

                    b.HasIndex("IdAlumno");

                    b.ToTable("AlertasAbandono");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.AsistenciaClase", b =>
                {
                    b.Property<int>("IdAsistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsistencia"));

                    b.Property<bool>("Asistio")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int");

                    b.HasKey("IdAsistencia");

                    b.HasIndex("IdReserva");

                    b.ToTable("AsistenciasClase");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.Campeonato", b =>
                {
                    b.Property<int>("IdCampeonato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCampeonato"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxParticipantes")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Reglas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdCampeonato");

                    b.ToTable("Campeonatos");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.Cancha", b =>
                {
                    b.Property<int>("IdCancha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCancha"));

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<bool>("EnMantenimiento")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCancha");

                    b.ToTable("Canchas");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.ClaseProgramada", b =>
                {
                    b.Property<int>("IdClaseProgramada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClaseProgramada"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaClase")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.HasKey("IdClaseProgramada");

                    b.HasIndex("IdCurso");

                    b.ToTable("ClasesProgramadas");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.ConfiguracionNotificacion", b =>
                {
                    b.Property<int>("IdConfiguracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConfiguracion"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Evento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdConfiguracion");

                    b.ToTable("ConfiguracionesNotificacion");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.ConsultaChatbot", b =>
                {
                    b.Property<int>("IdConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConsulta"));

                    b.Property<DateTime>("FechaConsulta")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUsuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MensajeUsuario")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RespuestaBot")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("Resuelto")
                        .HasColumnType("bit");

                    b.HasKey("IdConsulta");

                    b.HasIndex("IdUsuario");

                    b.ToTable("ConsultasChatbot");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.Cupon", b =>
                {
                    b.Property<int>("IdCupon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCupon"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdOferta")
                        .HasColumnType("int");

                    b.Property<int>("LimiteUsos")
                        .HasColumnType("int");

                    b.Property<int>("UsosActuales")
                        .HasColumnType("int");

                    b.HasKey("IdCupon");

                    b.HasIndex("IdOferta");

                    b.ToTable("Cupones");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.CuponUso", b =>
                {
                    b.Property<int>("IdUso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUso"));

                    b.Property<DateTime>("FechaUso")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCupon")
                        .HasColumnType("int");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdUso");

                    b.HasIndex("IdCupon");

                    b.HasIndex("IdUsuario");

                    b.ToTable("CuponUsos");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.Curso", b =>
                {
                    b.Property<int>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCurso"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CuposDisponibles")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("IdProfesor")
                        .HasColumnType("int");

                    b.Property<string>("IdProfesor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCurso");

                    b.HasIndex("IdProfesor");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.EncuestaSatisfaccion", b =>
                {
                    b.Property<int>("IdEncuesta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEncuesta"));

                    b.Property<int>("CalificacionClase")
                        .HasColumnType("int");

                    b.Property<int>("CalificacionInstalaciones")
                        .HasColumnType("int");

                    b.Property<int>("CalificacionProfesor")
                        .HasColumnType("int");

                    b.Property<string>("Comentarios")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("FechaEncuesta")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdAlumno")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int");

                    b.Property<string>("Recomendaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdEncuesta");

                    b.HasIndex("IdAlumno");

                    b.HasIndex("IdReserva");

                    b.ToTable("EncuestasSatisfaccion");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.Enfrentamiento", b =>
                {
                    b.Property<int>("IdEnfrentamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEnfrentamiento"));

                    b.Property<DateTime?>("FechaPartido")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCampeonato")
                        .HasColumnType("int");

                    b.Property<int?>("IdCancha")
                        .HasColumnType("int");

                    b.Property<string>("IdGanador")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdJugador1")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdJugador2")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Resultado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEnfrentamiento");

                    b.HasIndex("IdCampeonato");

                    b.HasIndex("IdCancha");

                    b.HasIndex("IdGanador");

                    b.HasIndex("IdJugador1");

                    b.HasIndex("IdJugador2");

                    b.ToTable("Enfrentamientos");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.Factura", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFactura"));

                    b.Property<DateTime>("FechaFactura")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPago")
                        .HasColumnType("int");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdFactura");

                    b.HasIndex("IdPago")
                        .IsUnique();

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.Horario", b =>
                {
                    b.Property<int>("IdHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHorario"));

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.HasKey("IdHorario");

                    b.HasIndex("IdCurso");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.InscripcionCampeonato", b =>
                {
                    b.Property<int>("IdInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInscripcion"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdAlumno")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdCampeonato")
                        .HasColumnType("int");

                    b.HasKey("IdInscripcion");

                    b.HasIndex("IdAlumno");

                    b.HasIndex("IdCampeonato");

                    b.ToTable("InscripcionesCampeonato");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.LogroAlumno", b =>
                {
                    b.Property<int>("IdLogro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLogro"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaObtencion")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdAlumno")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TipoLogro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdLogro");

                    b.HasIndex("IdAlumno");

                    b.ToTable("LogrosAlumno");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.Matricula", b =>
                {
                    b.Property<int>("IdMatricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMatricula"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaMatricula")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdAlumno")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.HasKey("IdMatricula");

                    b.HasIndex("IdAlumno");

                    b.HasIndex("IdCurso");

                    b.ToTable("Matriculas");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.Notificacion", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotificacion"));

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdNotificacion");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.Oferta", b =>
                {
                    b.Property<int>("IdOferta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOferta"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductosAplicables")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdOferta");

                    b.ToTable("Ofertas");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<bool>("EsManual")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdAlumno")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TipoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdPago");

                    b.HasIndex("IdAlumno");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.PreferenciaNotificacion", b =>
                {
                    b.Property<int>("IdPreferencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPreferencia"));

                    b.Property<string>("CanalPreferido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("NotificacionesCampeonato")
                        .HasColumnType("bit");

                    b.Property<bool>("NotificacionesClase")
                        .HasColumnType("bit");

                    b.Property<bool>("NotificacionesPago")
                        .HasColumnType("bit");

                    b.Property<bool>("NotificacionesRecordatorio")
                        .HasColumnType("bit");

                    b.HasKey("IdPreferencia");

                    b.HasIndex("IdUsuario");

                    b.ToTable("PreferenciasNotificacion");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.PreguntaFrecuente", b =>
                {
                    b.Property<int>("IdPregunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPregunta"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pregunta")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Respuesta")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("VecesConsultada")
                        .HasColumnType("int");

                    b.HasKey("IdPregunta");

                    b.ToTable("PreguntasFrecuentes");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PrecioAlquiler")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("IdProducto");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.Profesor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Profesores");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.ProgresoAlumno", b =>
                {
                    b.Property<int>("IdProgreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProgreso"));

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdAlumno")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdProfesor")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NivelDerecha")
                        .HasColumnType("int");

                    b.Property<string>("NivelGeneral")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NivelMovimiento")
                        .HasColumnType("int");

                    b.Property<int>("NivelReves")
                        .HasColumnType("int");

                    b.Property<int>("NivelSaque")
                        .HasColumnType("int");

                    b.Property<int>("NivelTactica")
                        .HasColumnType("int");

                    b.Property<int>("NivelVolea")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdProgreso");

                    b.HasIndex("IdAlumno");

                    b.HasIndex("IdProfesor");

                    b.ToTable("ProgresosAlumno");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.RachaAsistencia", b =>
                {
                    b.Property<int>("IdRacha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRacha"));

                    b.Property<string>("IdAlumno")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RachaActual")
                        .HasColumnType("int");

                    b.Property<int>("RachaMaxima")
                        .HasColumnType("int");

                    b.Property<int>("TotalClasesAsistidas")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("datetime2");

                    b.HasKey("IdRacha");

                    b.HasIndex("IdAlumno");

                    b.ToTable("RachasAsistencia");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<string>("IdAlumno")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdCancha")
                        .HasColumnType("int");

                    b.Property<string>("IdProfesor")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdReserva");

                    b.HasIndex("IdAlumno");

                    b.HasIndex("IdCancha");

                    b.HasIndex("IdProfesor");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.TransaccionProducto", b =>
                {
                    b.Property<int>("IdTransaccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTransaccion"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaTransaccion")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdAlumno")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("IdPago")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdTransaccion");

                    b.HasIndex("IdAlumno");

                    b.HasIndex("IdPago");

                    b.HasIndex("IdProducto");

                    b.ToTable("TransaccionesProducto");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.UbicacionAlumno", b =>
                {
                    b.Property<int>("IdUbicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUbicacion"));

                    b.Property<string>("DireccionCompleta")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("bit");

                    b.Property<string>("IdAlumno")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("IdZona")
                        .HasColumnType("int");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdUbicacion");

                    b.HasIndex("IdAlumno");

                    b.HasIndex("IdZona");

                    b.ToTable("UbicacionesAlumno");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.ZonaCobertura", b =>
                {
                    b.Property<int>("IdZona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdZona"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<decimal>("CostoAdicional")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdZona");

                    b.ToTable("ZonasCobertura");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.AlertaAbandono", b =>
                {
                    b.HasOne("AcademiaTennisDAL.Entities.ApplicationUser", "Alumno")
                        .WithMany()
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.AsistenciaClase", b =>
                {
                    b.HasOne("AcademiaTennisDAL.Entities.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.ClaseProgramada", b =>
                {
                    b.HasOne("AcademiaTennisDAL.Entities.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.ConsultaChatbot", b =>
                {
                    b.HasOne("AcademiaTennisDAL.Entities.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.Cupon", b =>
                {
                    b.HasOne("AcademiaTennisDAL.Entities.Oferta", "Oferta")
                        .WithMany("Cupones")
                        .HasForeignKey("IdOferta");

                    b.Navigation("Oferta");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.CuponUso", b =>
                {
                    b.HasOne("AcademiaTennisDAL.Entities.Cupon", "Cupon")
                        .WithMany("Usos")
                        .HasForeignKey("IdCupon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademiaTennisDAL.Entities.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cupon");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.Curso", b =>
                {
                    b.HasOne("AcademiaTennisDAL.Entities.Profesor", "Profesor")
                        .WithMany()
                        .HasForeignKey("IdProfesor");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.EncuestaSatisfaccion", b =>
                {
                    b.HasOne("AcademiaTennisDAL.Entities.ApplicationUser", "Alumno")
                        .WithMany()
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademiaTennisDAL.Entities.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.Enfrentamiento", b =>
                {
                    b.HasOne("AcademiaTennisDAL.Entities.Campeonato", "Campeonato")
                        .WithMany("Enfrentamientos")
                        .HasForeignKey("IdCampeonato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademiaTennisDAL.Entities.Cancha", "Cancha")
                        .WithMany()
                        .HasForeignKey("IdCancha");

                    b.HasOne("AcademiaTennisDAL.Entities.ApplicationUser", "Ganador")
                        .WithMany()
                        .HasForeignKey("IdGanador")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AcademiaTennisDAL.Entities.ApplicationUser", "Jugador1")
                        .WithMany()
                        .HasForeignKey("IdJugador1")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AcademiaTennisDAL.Entities.ApplicationUser", "Jugador2")
                        .WithMany()
                        .HasForeignKey("IdJugador2")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Campeonato");

                    b.Navigation("Cancha");

                    b.Navigation("Ganador");

                    b.Navigation("Jugador1");

                    b.Navigation("Jugador2");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.Factura", b =>
                {
                    b.HasOne("AcademiaTennisDAL.Entities.Pago", "Pago")
                        .WithOne("Factura")
                        .HasForeignKey("AcademiaTennisDAL.Entities.Factura", "IdPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.Horario", b =>
                {
                    b.HasOne("AcademiaTennisDAL.Entities.Curso", "Curso")
                        .WithMany("Horarios")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.InscripcionCampeonato", b =>
                {
                    b.HasOne("AcademiaTennisDAL.Entities.ApplicationUser", "Alumno")
                        .WithMany()
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademiaTennisDAL.Entities.Campeonato", "Campeonato")
                        .WithMany("Inscripciones")
                        .HasForeignKey("IdCampeonato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Campeonato");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.LogroAlumno", b =>
                {
                    b.HasOne("AcademiaTennisDAL.Entities.ApplicationUser", "Alumno")
                        .WithMany()
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.Matricula", b =>
                {
                    b.HasOne("AcademiaTennisDAL.Entities.ApplicationUser", "Alumno")
                        .WithMany()
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademiaTennisDAL.Entities.Curso", "Curso")
                        .WithMany("Matriculas")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.Notificacion", b =>
                {
                    b.HasOne("AcademiaTennisDAL.Entities.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.Pago", b =>
                {
                    b.HasOne("AcademiaTennisDAL.Entities.ApplicationUser", "Alumno")
                        .WithMany()
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.PreferenciaNotificacion", b =>
                {
                    b.HasOne("AcademiaTennisDAL.Entities.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.ProgresoAlumno", b =>
                {
                    b.HasOne("AcademiaTennisDAL.Entities.ApplicationUser", "Alumno")
                        .WithMany()
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademiaTennisDAL.Entities.ApplicationUser", "Profesor")
                        .WithMany()
                        .HasForeignKey("IdProfesor");

                    b.Navigation("Alumno");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.RachaAsistencia", b =>
                {
                    b.HasOne("AcademiaTennisDAL.Entities.ApplicationUser", "Alumno")
                        .WithMany()
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.Reserva", b =>
                {
                    b.HasOne("AcademiaTennisDAL.Entities.ApplicationUser", "Alumno")
                        .WithMany()
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademiaTennisDAL.Entities.Cancha", "Cancha")
                        .WithMany()
                        .HasForeignKey("IdCancha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademiaTennisDAL.Entities.ApplicationUser", "Profesor")
                        .WithMany()
                        .HasForeignKey("IdProfesor");

                    b.Navigation("Alumno");

                    b.Navigation("Cancha");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.TransaccionProducto", b =>
                {
                    b.HasOne("AcademiaTennisDAL.Entities.ApplicationUser", "Alumno")
                        .WithMany()
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademiaTennisDAL.Entities.Pago", "Pago")
                        .WithMany()
                        .HasForeignKey("IdPago");

                    b.HasOne("AcademiaTennisDAL.Entities.Producto", "Producto")
                        .WithMany("Transacciones")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Pago");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.UbicacionAlumno", b =>
                {
                    b.HasOne("AcademiaTennisDAL.Entities.ApplicationUser", "Alumno")
                        .WithMany()
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademiaTennisDAL.Entities.ZonaCobertura", "Zona")
                        .WithMany("Ubicaciones")
                        .HasForeignKey("IdZona");

                    b.Navigation("Alumno");

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AcademiaTennisDAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AcademiaTennisDAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcademiaTennisDAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AcademiaTennisDAL.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.Campeonato", b =>
                {
                    b.Navigation("Enfrentamientos");

                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.Cupon", b =>
                {
                    b.Navigation("Usos");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.Curso", b =>
                {
                    b.Navigation("Horarios");

                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.Oferta", b =>
                {
                    b.Navigation("Cupones");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.Pago", b =>
                {
                    b.Navigation("Factura");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.Producto", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("AcademiaTennisDAL.Entities.ZonaCobertura", b =>
                {
                    b.Navigation("Ubicaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
